---
title: "Summer 17 swap data"
author: "Erik Parker"
date: "August 27, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, tidy = TRUE)
```


```{r}

library(ggpubr)
library(gridExtra)
library(alr4)
library(ggsignif)
library(ggthemes)



swap.orig <- read.csv("Microbiome swap data - Sheet1.csv")


treatments <- swap.orig$Treatment.ID

# Separating the original data into male and female
swap.male <- swap.orig[swap.orig$Sex == "m",]
swap.female <- swap.orig[swap.orig$Sex == "f",]

dead <- swap.orig[swap.orig$Dead. == "y",]
alive <- swap.orig[swap.orig$Dead. == "",]

alive.female <- alive[alive$Sex == "f",]

alive.male <- alive[alive$Sex == "m",]


alive$Treatment.ID <- as.factor(alive$Treatment.ID)
alive$LT <- as.numeric(alive$LT)


gg <- swap.orig[swap.orig$Treatment.ID == "gg",]

gs <- swap.orig[swap.orig$Treatment.ID == "gs",]

ss <- swap.orig[swap.orig$Treatment.ID == "ss",]

sg <- swap.orig[swap.orig$Treatment.ID == "sg",]


gg.survival <- (nrow(gg) - (sum(gg$Dead. == "y"))) / nrow(gg)

gs.survival <- (nrow(gs) - (sum(gs$Dead. == "y"))) / nrow(gs)

ss.survival <- (nrow(ss) - (sum(ss$Dead. == "y"))) / nrow(ss)

sg.survival <- (nrow(sg) - (sum(sg$Dead. == "y"))) / nrow(sg)


gg.alive <- (nrow(gg) - (sum(gg$Dead. == "y")))

gs.alive <- (nrow(gs) - (sum(gs$Dead. == "y")))

ss.alive <- (nrow(ss) - (sum(ss$Dead. == "y")))

sg.alive <- (nrow(sg) - (sum(sg$Dead. == "y")))

survivals <- c(gg.survival,gs.survival,ss.survival,sg.survival)
survivals <- as.data.frame(survivals)
survivals$treatment <- c("gg", "gs", "ss", "sg")
survivals$species <- c("Gazella", "Gazella", "Sagittarius", "Sagittarius")
survivals$microbiome <- c("Gazella", "Sagittarius", "Sagittarius", "Gazella")
survivals$alive <- c(gg.alive,gs.alive,ss.alive,sg.alive)


fun_length <- function(x){
  return(data.frame(y=median(x),label= paste0("n=", length(x))))
}


a <- ggplot(alive, aes(x = Treatment.ID, y = LT)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to L3 for survivors only")

a

c <- ggplot(alive, aes(x = Treatment.ID, y = LW)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.1, size = 4) + labs(title = "Weight at L3 day 3 for survivors only")

e <- ggplot(alive, aes(x = Treatment.ID, y = PT)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to pupation for survivors only")

g <- ggplot(alive, aes(x = Treatment.ID, y = PW)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.1, size = 4) + labs(title = "Weight at P day 3 for survivors only")

# Analyses done with individuals who died before adulthood


b <- ggplot(swap.orig, aes(x = Treatment.ID, y = LT)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to L3 for all individuals")

b

d <- ggplot(swap.orig, aes(x = Treatment.ID, y = LW)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.1, size = 4) + labs(title = "Weight at L3 day 3 for all individuals")

f <- ggplot(swap.orig, aes(x = Treatment.ID, y = PT)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to pupation for all individuals")

h <- ggplot(swap.orig, aes(x = Treatment.ID, y = PW)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.1, size = 4) + labs(title = "Weight at P day 3 for all individuals")


grid.arrange(a,b, ncol = 2)
grid.arrange(c,d, ncol = 2)
grid.arrange(e,f, ncol = 2)
grid.arrange(g,h, ncol = 2)


ae <- ggplot(alive, aes(x = Treatment.ID, y = AT)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to adult eclosion")

tw <- ggplot(alive, aes(x = Treatment.ID, y = ATW)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Adult thorax width")

ggplot(survivals, aes(x = treatment, y = survivals)) + geom_point() + expand_limits(y = 0)

# two-proportions z-test, tests for significance in difference between porpotions for two populations that are:
# independent, large enough (>=5) (sg?), randomly selected. 
ggvgs.surv <- prop.test(x = c((nrow(gg) - (sum(gg$Dead. == "y"))), (nrow(gs) - (sum(gs$Dead. == "y")))), n = c(nrow(gg), nrow(gs)))

ggvgs.surv

ssvsg.surv <- prop.test(x = c((nrow(ss) - (sum(ss$Dead. == "y"))), (nrow(sg) - (sum(sg$Dead. == "y")))), n = c(nrow(ss), nrow(sg)))

ssvsg.surv


# Adult metrics seperately reported for males and females

me <- ggplot(alive.male, aes(x = Treatment.ID, y = AT)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to adult eclosion - males only")

fe <- ggplot(alive.female, aes(x = Treatment.ID, y = AT)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to adult eclosion - females only")

mfe <- grid.arrange(me,fe, ncol = 2)

grid.arrange(ae, mfe)



mw <- ggplot(alive.male, aes(x = Treatment.ID, y = ATW)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Adult thorax width - males only")

fw <- ggplot(alive.female, aes(x = Treatment.ID, y = ATW)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Adult thorax width - females only")

mfw <- grid.arrange(mw,fw, ncol = 2)

grid.arrange(tw, mfw)


# So, females are the ones eclosing later and coming out smaller for the most part.  Males don't show any real significant difference.  Opposite of what other studies in the lab seem to have shown when looking at sex differences, where males are more responsive to fitness challenges.  Most likely explanation is that my data are wrong and the existing evidence is correct.


# Below plots for pupal time of males and females
mp <- ggplot(swap.male, aes(x = Treatment.ID, y = PT)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to Pupation - males only")

fp <- ggplot(swap.female, aes(x = Treatment.ID, y = PT)) + geom_boxplot() + stat_compare_means(method = "wilcox.test", comparisons = list(c("gg","gs"), c("sg","ss"))) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to Pupation - females only")

mfp <- grid.arrange(mp,fp, ncol = 2)

grid.arrange(f, mfp)




```



```{r}

gazella.data <- rbind(gg,gs)

#removing individual with pupal time, but not weight
gazella.data <- gazella.data[-20,]

gazella.male <- gazella.data[gazella.data$Sex == "m",]
gazella.female <- gazella.data[gazella.data$Sex == "f",]

fun_length <- function(x){
  return(data.frame(y=median(x),label= paste0("n=", length(x))))
}

# Plot for gazella pupal time
pt <- ggplot(gazella.data, aes(x = Treatment.ID, y = PT)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", textsize = 6, vjust = 2) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.3, size = 4) + labs(title = "Days to pupation for all individuals", x = "Treatment Group", y = "Days") + 
  theme(plot.title = element_text(family = "Trebuchet MS", face="bold", size=16, hjust=0)) +
  theme(axis.title = element_text(family = "Trebuchet MS", size=14)) + theme(axis.text=element_text(size=14))

#mp <- ggplot(gazella.male, aes(x = Treatment.ID, y = PT)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", textsize = 6, vjust = 2) +
#  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
#               vjust = +1.3, size = 4) + labs(title = "Time to Pupation - males only")+ 
#  theme(plot.title = element_text(family = "Trebuchet MS", face="bold", size=16, hjust=0)) +
#  theme(axis.title = element_text(family = "Trebuchet MS", size=12)) + theme(axis.text=element_text(size=12))

#fp <- ggplot(gazella.female, aes(x = Treatment.ID, y = PT)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", textsize = 6, vjust = 2) +
#  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
#               vjust = +1.3, size = 4) + labs(title = "Time to Pupation - females only")+ 
#  theme(plot.title = element_text(family = "Trebuchet MS", face="bold", size=16, hjust=0)) +
#  theme(axis.title = element_text(family = "Trebuchet MS", size=12)) + theme(axis.text=element_text(size=12))

#mfp <- grid.arrange(mp,fp, ncol = 2)

#grid.arrange(pt, mfp)


# Weight at pupa day 3

pw <- ggplot(gazella.data, aes(x = Treatment.ID, y = PW)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", textsize = 6, vjust = 2) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.2, size = 4) + labs(title = "Weight at pupa day 3 for all individuals")+ 
  theme(plot.title = element_text(family = "Trebuchet MS", face="bold", size=16, hjust=0)) +
  theme(axis.title = element_text(family = "Trebuchet MS", size=12)) + theme(axis.text=element_text(size=12))
pw

# Time to adult eclosion

ae <- ggplot(gazella.data, aes(x = Treatment.ID, y = AT)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", textsize = 6, vjust = 2) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to adult eclosion")+ 
  theme(plot.title = element_text(family = "Trebuchet MS", face="bold", size=16, hjust=0)) +
  theme(axis.title = element_text(family = "Trebuchet MS", size=12)) + theme(axis.text=element_text(size=12))

me <- ggplot(gazella.male, aes(x = Treatment.ID, y = AT)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", textsize = 6, vjust = 2) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to adult eclosion - males only")+ 
  theme(plot.title = element_text(family = "Trebuchet MS", face="bold", size=16, hjust=0)) +
  theme(axis.title = element_text(family = "Trebuchet MS", size=12)) + theme(axis.text=element_text(size=12))

fe <- ggplot(gazella.female, aes(x = Treatment.ID, y = AT)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", textsize = 6, vjust = 2) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text",
               vjust = +1.5, size = 4) + labs(title = "Time to adult eclosion - females only")+ 
  theme(plot.title = element_text(family = "Trebuchet MS", face="bold", size=16, hjust=0)) +
  theme(axis.title = element_text(family = "Trebuchet MS", size=12)) + theme(axis.text=element_text(size=12))

mfe <- grid.arrange(me,fe, ncol = 2)

grid.arrange(ae, mfe)

# Survivals



ggvgs.surv <- prop.test(x = c((nrow(gg) - (sum(gg$Dead. == "y"))), (nrow(gs) - (sum(gs$Dead. == "y")))), n = c(nrow(gg), nrow(gs)))

ggvgs.surv

ssvsg.surv <- prop.test(x = c((nrow(ss) - (sum(ss$Dead. == "y"))), (nrow(sg) - (sum(sg$Dead. == "y")))), n = c(nrow(ss), nrow(sg)))

ssvsg.surv

```

```{r}

theme_Publication <- function(base_size=14, base_family="helvetica") {
      library(grid)
      library(ggthemes)
      (theme_foundation(base_size=base_size, base_family=base_family)
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA, size = 5),
               legend.position = "right",
               legend.direction = "vertical",
               legend.key.size= unit(0.7, "cm"),
               legend.margin = unit(0, "cm"),
               legend.title = element_text(face="italic"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
          ))
      
}

scale_fill_Publication <- function(...){
      library(scales)
      discrete_scale("fill","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

scale_colour_Publication <- function(...){
      library(scales)
      discrete_scale("colour","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

```

```{r}

# Plot for gazella pupal time

#pt <- ggplot(gazella.data, aes(x = Treatment.ID, y = PT)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", textsize = 8, vjust = 2) +
#  scale_x_discrete(labels = c("Gazella", "Sagittarius")) +
#  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(0.9), fun.data = fun_length,  geom = "text",
#               vjust = +1.4, size = 6, hjust = -0.2) + labs(title = "Days until pupation", x = "Microbiome ID", y = "Days") + 
#  theme(plot.title = element_text(family = "Trebuchet MS", face="bold", size=18, hjust=+0.5)) +
#  theme(axis.title = element_text(family = "Trebuchet MS", size=16)) + theme(axis.text=element_text(size=16))


pt <- ggplot(gazella.data, aes(x = Treatment.ID, y = PT)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", map_signif_level = TRUE) +
  scale_x_discrete(labels = c("Gazella", "Sagittarius")) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(0.9), fun.data = fun_length,  geom = "text",
               vjust = +1.4, hjust = -0.2) + labs(title = "Days until pupation", x = "Microbiome ID", y = "Days") + 
  theme_Publication()

# Theme publication argument seems to result in the best plots


# Weight at pupa day 3

#pw <- ggplot(gazella.data, aes(x = Treatment.ID, y = PW)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", textsize = 6, vjust = 2) +
#  scale_x_discrete(labels = c("Gazella", "Sagittarius")) +
#  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text", vjust = +1.4, size = 4) + labs(title = "Weight at pupa day 3", x = "Microbiome ID", y = "Weight (g)")+ 
#  theme(plot.title = element_text(family = "Trebuchet MS", face="bold", size=16, hjust=+0.5)) +
#  theme(axis.title = element_text(family = "Trebuchet MS", size=14)) + theme(axis.text=element_text(size=14))

pw <- ggplot(gazella.data, aes(x = Treatment.ID, y = PW)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", map_signif_level = TRUE) +
  scale_x_discrete(labels = c("Gazella", "Sagittarius")) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text", vjust = -.4) + labs(title = "Weight at pupa day 3", x = "Microbiome ID", y = "Weight (g)") + theme_Publication()



# Time to adult eclosion

#ae <- ggplot(gazella.data, aes(x = Treatment.ID, y = AT)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", textsize = 6, vjust = 2) +
#  scale_x_discrete(labels = c("Gazella", "Sagittarius")) +
#  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text", vjust = +1.4, size = 4) + labs(title = "Days until adult eclosion", x = "Microbiome ID", y = "Days")+ 
#  theme(plot.title = element_text(family = "Trebuchet MS", face="bold", size=16, hjust=+0.5)) +
#  theme(axis.title = element_text(family = "Trebuchet MS", size=14)) + theme(axis.text=element_text(size=14))

ae <- ggplot(gazella.data, aes(x = Treatment.ID, y = AT)) + geom_boxplot() + geom_signif(comparisons = list(c("gg","gs")), test = "wilcox.test", map_signif_level = TRUE) +
  scale_x_discrete(labels = c("Gazella", "Sagittarius")) +
  stat_summary(aes(x=factor(Treatment.ID)), position=position_dodge(.9), fun.data = fun_length,  geom = "text", vjust = +1.4) + labs(title = "Days until adult eclosion", x = "Microbiome ID", y = "Days")+ 
  theme_Publication()


# Final plot for growth metrics
ggarrange(pt,pw,ae, ncol = 3, labels = c("A","B","C"))




# Plot of survivals

#making custom sig values first

pv_final <- as.data.frame(c(ssvsg.surv$p.value))
pv_final$names <- c("Sag")
pv_final$map_signif <- ifelse(pv_final$`c(ssvsg.surv$p.value)` > 0.05, "", ifelse(pv_final$`c(ssvsg.surv$p.value)` > 0.01,"*", "**"))  


ggplot(survivals, aes(x = species, y = survivals, fill = microbiome)) + geom_col(position = "dodge") + expand_limits(y = 0)+ 
  theme_Publication() + labs(x = "Focal Host Species", y = "Survival Rate", title = "Rates of Survival to Adulthood") + geom_signif(comparisons = list(c("Sagittarius","Sagittarius")), annotations = pv_final$map_signif, textsize = 8, vjust = 2) + scale_fill_grey()

ggplot(survivals, aes(x = species, y = survivals, fill = microbiome)) + geom_col(position = "dodge") + expand_limits(y = 0)+ 
  theme_Publication() + labs(x = "Focal Host Species", y = "Survival Rate", title = "Rates of Survival to Adulthood") + geom_signif(comparisons = list(c(survivals$treatment == "ss", survivals$treatment == "sg")), test = "prop.test") 


```